### ISSUE TITLE
Follow GPL v2

### ISSUE THREAD

**Issue by Tatamo** [FreecivJapan/freeciv-docker#1]
this project contains the code licensed under GPL v2 (e.g. [/rulesets/default/default.lua](https://github.com/FreecivJapan/freeciv-docker/blob/master/rulesets/default/default.lua)).
it means that the entire project is also under GPL, doesnt it?
this repository should add LICENSE file and follow GPL explicitly.

**Comment by sensu-watson** [comment]
add LICENSE file at commit 6c59b90efd4f92cca17154a7f529548b977d0e57.
